version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Copying files to build directory"
      # Add your actual build commands here
      - echo "Build started on $(date)"
      - mkdir -p dist
      - cp *.html dist/ || true
      - cp *.css dist/ || true
      - cp *.js dist/ || true
      - cp -r assets/ dist/ || true
      
artifacts:
  files:
    - '**/*.html'
    - '**/*.css'
    - '**/*.js'
    - 'scripts/**/*'
    - 'images/**/*'
    - 'apps/**/*'
    - 'appspec.yml'  
  base-directory: 'dist'  # Point to your build output directory if applicable
  discard-paths:no

