version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Copying files to build directory"
      - mkdir -p dist
      - cp *.html dist/ || true
      - cp *.css dist/ || true
      - cp *.js dist/ || true
      - cp -r assets/ dist/ || true
      - cp -r scripts/ dist/ || true
      - cp -r images/ dist/ || true
      - cp appspec.yml dist/ || true

artifacts:
  files:
    - '**/*.html'
    - '**/*.css'
    - '**/*.js'
    - 'scripts/**/*'
    - 'images/**/*'
    - 'apps/**/*'
    - 'appspec.yml'
  base-directory: 'dist'
  discard-paths: no
